name: Standalone CLI
on: [push, pull_request]

jobs:
  machineStandalone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Fluid Attacks SAST with config file
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/project \
            fluidattacks/sast:latest \
            sast scan /project/config.yaml
