name: Doker Image CI

on:
   push:
      branches: [ main ]
   pull_request:
     branches: [ main ]

jobs:
  forces:
    runs-on: ubuntu-latest
    container:
      image: fluidattacks/forces:latest
      env:
        TOKEN: <secrets.TOKENF>
    steps:
      - name: Run Agent check
        run: forces --token ${tokenf} --strict --dynamic -breaking 1.0
